nelmio_api_doc:
    documentation:
        info:
            title: E-proxi API
            description: E-proxi API doc
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/.eproxi/api(?!/doc) # Accepts routes under /api except /api/doc
    models: { use_jms: false }